// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/thomasmortensson/pxe-init/internal/domain/entities"
)

// ListImagesUseCase is an autogenerated mock type for the ListImagesUseCase type
type ListImagesUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *ListImagesUseCase) Execute() ([]*entities.Image, error) {
	ret := _m.Called()

	var r0 []*entities.Image
	if rf, ok := ret.Get(0).(func() []*entities.Image); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
