// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePxeInitServer is an autogenerated mock type for the UnsafePxeInitServer type
type UnsafePxeInitServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPxeInitServer provides a mock function with given fields:
func (_m *UnsafePxeInitServer) mustEmbedUnimplementedPxeInitServer() {
	_m.Called()
}
