apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.addressPool }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.label }}
